Ahd develop
FanapSoft/pod-chat-android-test-app pull request #1
Opened 2020-09-09 06:23 UTC by masoudmanson

2020-09-09 06:56 UTC, Farhad7d7 approved these changes
Done

2020-09-09 06:58 UTC, Farhad7d7 commented on app/src/main/java/ir/fanap/chattestapp/application/ui/function/FunctionFragment.kt
> -            .deleteForAll(false)
?

2020-09-09 06:59 UTC, Farhad7d7 commented on app/src/main/java/ir/fanap/chattestapp/application/ui/function/FunctionFragment.kt
> +          //  changeFunTwoState(position, Method.RUNNING)
FunTwoState should change to RUNNING

2020-09-09 07:17 UTC, Farhad7d7 requested changes
Check Comments

2020-09-14 12:11 UTC, ahd2254 commented on app/src/main/java/ir/fanap/chattestapp/application/ui/function/FunctionFragment.kt
> -            .deleteForAll(false)
ok

2020-09-14 12:12 UTC, ahd2254 commented on app/src/main/java/ir/fanap/chattestapp/application/ui/function/FunctionFragment.kt
> +          //  changeFunTwoState(position, Method.RUNNING)
ok

2020-09-20 10:15 UTC, merged